# With GitHub Pages Gem
remote_theme: chrisrhymes/bulma-clean-theme

# Site Settings
lang: ja
title: Ruby合宿 公式サイト
tagline: Ruby合宿
email: rubycamp@eastback.jp
description: >
  島根県主催 Ruby合宿 公式サイト
baseurl: ""
url: ""
permalink: pretty
favicon: /image/favicon/favicon.ico
#gh_sponsor: chrisrhymes
#hide_share_buttons: true
theme_color: '#EA454B'
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

#paginate: 5
#paginate_path: "/blog/page:num"

# Disqus Comments
disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  shortname: 

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

google_analytics: UA-41194407-2

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "RubyCamp"
      layout: post
      show_sidebar: false

markdown: kramdown
highlighter: rouge

footer_menu: footer_menu

collections:
  news: 
    output: true
  reports: 
    output: true
  blog: 
    output: true
